'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '../../lib/supabase';
import styles from '../admin.module.css';
import {readableTextColor} from '../../lib/colorContrast';
const blank={name:'',slug:'',description:'',theme_name:'Pop Style',theme_color:'#ff70a6',accent_color:'#ffe05c',icon:'📚',is_active:true};
const slugify=s=>s.toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
export default function GenreForm({id}){const router=useRouter();const [form,setForm]=useState(blank),[error,setError]=useState(''),[busy,setBusy]=useState(false),[slugTouched,setSlugTouched]=useState(false);
 useEffect(()=>{if(id)supabase.from('genres').select('*').eq('id',id).single().then(({data,error})=>error?setError(error.message):setForm(data))},[id]);
 const set=(key,value)=>setForm(v=>({...v,[key]:value})); async function submit(e){e.preventDefault();setError('');if(!form.name.trim()||!form.slug.trim())return setError('Nama dan slug wajib diisi.');setBusy(true);const query=id?supabase.from('genres').update(form).eq('id',id):supabase.from('genres').insert(form);const {error}=await query;setBusy(false);if(error)return setError(error.message);router.push('/admin/genres?success='+(id?'updated':'created'));router.refresh()}
 return <form className={`${styles.card} ${styles.form}`} onSubmit={submit}>{error&&<div className={styles.error}>{error}</div>}<div className={styles.row}><label className={styles.field}>Nama genre *<input className={styles.input} value={form.name} onChange={e=>{set('name',e.target.value);if(!slugTouched)set('slug',slugify(e.target.value))}} required/></label><label className={styles.field}>Slug *<input className={styles.input} value={form.slug} onChange={e=>{setSlugTouched(true);set('slug',slugify(e.target.value))}} required/></label></div><label className={styles.field}>Deskripsi<textarea className={styles.textarea} value={form.description||''} onChange={e=>set('description',e.target.value)}/></label><div className={styles.row}><label className={styles.field}>Nama tema<input className={styles.input} value={form.theme_name||''} onChange={e=>set('theme_name',e.target.value)}/></label><label className={styles.field}>Icon<input className={styles.input} value={form.icon||''} onChange={e=>set('icon',e.target.value)}/></label><label className={styles.field}>Warna utama<input className={styles.input} type="color" value={form.theme_color||'#ffffff'} onChange={e=>set('theme_color',e.target.value)}/></label><label className={styles.field}>Warna aksen<input className={styles.input} type="color" value={form.accent_color||'#ffffff'} onChange={e=>set('accent_color',e.target.value)}/></label></div><label className={styles.field}>Status<select className={styles.select} value={String(form.is_active)} onChange={e=>set('is_active',e.target.value==='true')}><option value="true">Aktif</option><option value="false">Nonaktif</option></select></label><div className={styles.preview} style={{background:form.theme_color,color:readableTextColor(form.theme_color),borderColor:'#111'}}><b>{form.icon} {form.name||'Preview Genre'}</b><p>{form.theme_name}</p><span className={styles.badge} style={{background:form.accent_color}}>NEOBRUTAL</span></div><button className={styles.button} disabled={busy}>{busy?'Menyimpan...':'Simpan Genre'}</button></form>}
